import type { Game } from "./types"

// Sample dataset of Roblox games
export const robloxGames: Game[] = [
  {
    id: "920587237",
    name: "Adopt Me!",
    description: "Adopt and raise cute pets, trade items, and build your dream home in this popular role-playing game.",
    creator: "Uplift Games",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Adopt+Me!",
    playing: 150000,
    visits: 32000000000,
    likes: 94,
    rating: 4.8,
    genres: ["Role-Playing", "Adventure", "Social"],
    releaseDate: "2017-07-14",
    lastUpdated: "2023-12-15",
    content:
      "Adopt Me is a role-playing game where players can adopt and raise pets, trade items, and build and decorate their homes. The game features regular updates with new pets, items, and areas to explore. Players can hatch eggs to get pets of varying rarities and age them up through different life stages. The game includes mini-games, quests, and special events.",
  },
  {
    id: "2753915549",
    name: "Blox Fruits",
    description:
      "Become a powerful pirate or marine in this One Piece inspired adventure game with Devil Fruits and combat.",
    creator: "Gamer Robot Inc",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Blox+Fruits",
    playing: 120000,
    visits: 12000000000,
    likes: 96,
    rating: 4.7,
    genres: ["Fighting", "Adventure", "Anime"],
    releaseDate: "2019-01-25",
    lastUpdated: "2023-11-30",
    content:
      "Blox Fruits is an adventure fighting game inspired by the anime One Piece. Players can choose to be a pirate or marine, collect Devil Fruits that grant special abilities, and engage in combat with other players or NPCs. The game features a large open world with different islands to explore, bosses to defeat, and weapons to master. Players can level up their characters, unlock new abilities, and participate in raids.",
  },
  {
    id: "4924922222",
    name: "Brookhaven RP",
    description: "Live your dream life in this role-playing town with houses, vehicles, and jobs.",
    creator: "Wolfpaq",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Brookhaven+RP",
    playing: 200000,
    visits: 18000000000,
    likes: 92,
    rating: 4.5,
    genres: ["Role-Playing", "Town & City", "Social"],
    releaseDate: "2020-04-10",
    lastUpdated: "2023-10-20",
    content:
      "Brookhaven RP is a role-playing game where players can live their dream life in a virtual town. Players can choose from a variety of houses, vehicles, and jobs. The game features a school, hospital, police station, and other locations typical of a small town. Players can customize their avatars, interact with other players, and participate in community events.",
  },
  {
    id: "3956818381",
    name: "Pet Simulator X",
    description: "Collect pets, hatch eggs, and explore unique worlds in this pet collecting simulator.",
    creator: "BIG Games",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Pet+Simulator+X",
    playing: 90000,
    visits: 9000000000,
    likes: 95,
    rating: 4.6,
    genres: ["Simulator", "Collecting", "Pet"],
    releaseDate: "2021-07-17",
    lastUpdated: "2023-12-10",
    content:
      "Pet Simulator X is a game where players collect pets, hatch eggs, and explore unique worlds. Players can collect coins and gems to purchase eggs that hatch into pets with different rarities and abilities. Pets can be upgraded, enchanted, and fused to create more powerful companions. The game features regular updates with new areas, pets, and features.",
  },
  {
    id: "6284583030",
    name: "Murder Mystery 2",
    description: "Classic murder mystery game where players are assigned roles as innocent, sheriff, or murderer.",
    creator: "Nikilis",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Murder+Mystery+2",
    playing: 70000,
    visits: 8000000000,
    likes: 93,
    rating: 4.5,
    genres: ["Mystery", "Horror", "Social"],
    releaseDate: "2014-01-18",
    lastUpdated: "2023-09-05",
    content:
      "Murder Mystery 2 is a classic murder mystery game where players are assigned one of three roles: innocent, sheriff, or murderer. Innocents must survive and help identify the murderer, the sheriff must protect innocents and eliminate the murderer, and the murderer must eliminate everyone without getting caught. The game features a variety of maps, weapons, and cosmetics to collect.",
  },
  {
    id: "4872321990",
    name: "Arsenal",
    description: "Fast-paced first-person shooter with a variety of weapons and game modes.",
    creator: "ROLVe Community",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Arsenal",
    playing: 60000,
    visits: 5000000000,
    likes: 91,
    rating: 4.4,
    genres: ["Shooter", "FPS", "Action"],
    releaseDate: "2015-08-18",
    lastUpdated: "2023-11-15",
    content:
      "Arsenal is a fast-paced first-person shooter game with a variety of weapons and game modes. Players progress through a series of weapons by eliminating opponents, with the goal of being the first to get a kill with the final weapon. The game features multiple maps, game modes, and a wide selection of weapons to master.",
  },
  {
    id: "2788229376",
    name: "Royale High",
    description: "Fantasy role-playing game centered around a magical high school with realms to explore and events.",
    creator: "callmehbob",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Royale+High",
    playing: 80000,
    visits: 7000000000,
    likes: 94,
    rating: 4.7,
    genres: ["Role-Playing", "Fantasy", "Social"],
    releaseDate: "2017-11-20",
    lastUpdated: "2023-12-01",
    content:
      "Royale High is a fantasy role-playing game centered around a magical high school. Players can attend classes, explore various realms, collect items, and participate in seasonal events. The game features a detailed character customization system, a trading system for rare items, and mini-games to earn in-game currency.",
  },
  {
    id: "4490140733",
    name: "Welcome to Bloxburg",
    description: "Build your dream home, work jobs, and live a virtual life in this town & city role-playing game.",
    creator: "Coeptus",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Welcome+to+Bloxburg",
    playing: 75000,
    visits: 6000000000,
    likes: 95,
    rating: 4.8,
    genres: ["Role-Playing", "Town & City", "Building"],
    releaseDate: "2014-12-26",
    lastUpdated: "2023-10-10",
    content:
      "Welcome to Bloxburg is a life simulation game where players can build their dream home, work various jobs, and live a virtual life. The game features an advanced building system, multiple jobs to earn money, and social activities to engage with other players. Players can customize their homes, vehicles, and avatars to express their creativity.",
  },
  {
    id: "3101667897",
    name: "Jailbreak",
    description: "Choose between being a criminal or police officer in this open-world game with robberies and chases.",
    creator: "Badimo",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Jailbreak",
    playing: 65000,
    visits: 7500000000,
    likes: 92,
    rating: 4.6,
    genres: ["Adventure", "Action", "Open World"],
    releaseDate: "2017-04-21",
    lastUpdated: "2023-11-25",
    content:
      "Jailbreak is an open-world game where players can choose to be criminals or police officers. Criminals can escape from prison, rob various locations, and evade capture, while police officers can arrest criminals and prevent robberies. The game features a variety of vehicles, weapons, and locations to explore. Regular updates add new content, vehicles, and robbery locations.",
  },
  {
    id: "6447798030",
    name: "Doors",
    description: "Horror escape game where players navigate through a series of rooms while avoiding entities.",
    creator: "LSPLASH",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Doors",
    playing: 55000,
    visits: 2500000000,
    likes: 97,
    rating: 4.9,
    genres: ["Horror", "Adventure", "Puzzle"],
    releaseDate: "2022-08-15",
    lastUpdated: "2023-09-30",
    content:
      "Doors is a horror escape game where players navigate through a series of rooms while avoiding entities. Each door leads to a new room with potential dangers and puzzles to solve. The game features unique monsters with different mechanics, items to collect and use, and an eerie atmosphere that keeps players on edge.",
  },
  {
    id: "7991339063",
    name: "Tower of Hell",
    description: "Challenging obby (obstacle course) with randomly generated levels and a time limit.",
    creator: "YXCeptional Studios",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Tower+of+Hell",
    playing: 50000,
    visits: 4000000000,
    likes: 90,
    rating: 4.3,
    genres: ["Obby", "Platformer", "Challenge"],
    releaseDate: "2018-07-05",
    lastUpdated: "2023-08-20",
    content:
      "Tower of Hell is a challenging obstacle course game with randomly generated levels and a time limit. Players must climb to the top of the tower while avoiding obstacles and traps. The game features a variety of difficulty levels, power-ups, and customization options. Unlike traditional obbies, Tower of Hell has no checkpoints, making it a true test of skill and perseverance.",
  },
  {
    id: "6284583030",
    name: "Piggy",
    description: "Horror survival game inspired by Peppa Pig and Granny, with puzzles and a mysterious storyline.",
    creator: "MiniToon",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Piggy",
    playing: 45000,
    visits: 3500000000,
    likes: 94,
    rating: 4.7,
    genres: ["Horror", "Survival", "Puzzle"],
    releaseDate: "2020-01-25",
    lastUpdated: "2023-07-15",
    content:
      "Piggy is a horror survival game inspired by Peppa Pig and Granny. Players must escape from various maps while avoiding the Piggy and solving puzzles. The game features a mysterious storyline that unfolds across multiple chapters, different game modes, and a variety of characters with unique abilities.",
  },
  {
    id: "8737602449",
    name: "Bee Swarm Simulator",
    description: "Collect bees, gather pollen, and make honey in this unique simulator game.",
    creator: "Onett",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Bee+Swarm+Simulator",
    playing: 40000,
    visits: 3000000000,
    likes: 96,
    rating: 4.8,
    genres: ["Simulator", "Collecting", "Adventure"],
    releaseDate: "2018-03-23",
    lastUpdated: "2023-06-10",
    content:
      "Bee Swarm Simulator is a game where players collect bees, gather pollen from flowers, and make honey. Players can discover and hatch different types of bees, each with unique abilities and stats. The game features various fields to collect pollen from, quests to complete, and bosses to defeat. Players can also craft items, upgrade their equipment, and explore different areas of the map.",
  },
  {
    id: "5926001758",
    name: "Phantom Forces",
    description: "Advanced first-person shooter with realistic physics and a variety of weapons and maps.",
    creator: "StyLiS Studios",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Phantom+Forces",
    playing: 35000,
    visits: 2800000000,
    likes: 93,
    rating: 4.6,
    genres: ["Shooter", "FPS", "Action"],
    releaseDate: "2015-12-01",
    lastUpdated: "2023-12-05",
    content:
      "Phantom Forces is an advanced first-person shooter game with realistic physics and a variety of weapons and maps. Players can choose from different classes, customize their loadouts, and engage in team-based combat. The game features multiple game modes, a progression system to unlock new weapons and attachments, and detailed weapon mechanics.",
  },
  {
    id: "4623386862",
    name: "Piggy Build Mode",
    description: "Create and share your own Piggy maps with traps, items, and custom gameplay.",
    creator: "MiniToon",
    thumbnail: "/placeholder.svg?height=200&width=400&text=Piggy+Build+Mode",
    playing: 30000,
    visits: 2000000000,
    likes: 95,
    rating: 4.7,
    genres: ["Building", "Horror", "Creative"],
    releaseDate: "2020-05-10",
    lastUpdated: "2023-05-20",
    content:
      "Piggy Build Mode is a creative game where players can design and share their own Piggy maps. Players can place traps, items, and NPCs to create challenging gameplay experiences. The game features a variety of building tools, customization options, and the ability to play and rate maps created by other players.",
  },
]
